version: "2.1"

services:
  spark:
    build: docker/build/jupyter
    container_name: spark
    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks/
    networks:
      stock_analytics:
        ipv4_address: 172.27.0.22

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    expose:
      - "8080"
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.27.0.12
      KAFKA_ZOOKEEPER_CONNECT: 172.27.0.32:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.27.0.12:9092
      KAFKA_LISTENERS: PLAINTEXT://172.27.0.12:9092
    networks:
      stock_analytics:
        ipv4_address: 172.27.0.12
    depends_on:
      - "zookeeper"

  zookeeper:
      image: wurstmeister/zookeeper:latest
      container_name: zookeeper
      expose:
        - "2181"
      networks:
        stock_analytics:
          ipv4_address: 172.27.0.32

  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    container_name: kafka_manager
    expose:
      - "9000"
    environment:
      ZK_HOSTS: "172.27.0.32:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    depends_on:
      - "zookeeper"
      - "kafka"
    networks:
      stock_analytics:
        ipv4_address: 172.27.0.44

  db:
    build: docker/build/postgresql
    image: stockanalytics/postgresql
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
      - ./volumes/data:/opt/data
    tmpfs:
      - /run
      - /tmp
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      stock_analytics:
        ipv4_address: 172.27.0.55

  elasticsearch:
    build: ./docker/build/elasticsearch
    image: stockanalytics/elasticsearch
    container_name: elasticsearch
    volumes:
      - ./docker/build/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      stock_analytics:
        ipv4_address: 172.27.0.88

  kibana:
    build: ./docker/build/kibana
    image: stockanalytics/kibana
    container_name: kibana
    volumes:
      - ./docker/build/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      stock_analytics:
        ipv4_address: 172.27.0.99
    depends_on:
      - elasticsearch

networks:
  stock_analytics:
    name: stock_analytics
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
